server:
  port: 8000
spring:
  application:
    name: hui-controller-manager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/codepulse?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: your_db_name
    password: your_db_password
    hikari:
      max-lifetime: 60000
      connection-timeout: 10000
      validation-timeout: 3000
      maximum-pool-size: 10
      minimum-idle: 5
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    log_exchange: flow.log
    log_routing_key: flow.operation.log
mybatis:
  type-handlers-package: com.github.aborn.codepulse.mybatis
  configuration:
    map-underscore-to-camel-case: true