server:
  port: 8001
  session-timeout: 1800

logging:
  file:
    name: packages/codepulse.log
spring:
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false

